version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules #directing to not include this for mounting
      - .:/home/node/app # we are mounting the current working local directory to the directory in the container, so that if there are any changes than in local it will be automcatically sensed by running container, and if we refresh the browser we can see those changes.
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
